source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.2'
use_frameworks!

workspace 'BoostlingoSdk.xcworkspace'

target 'BoostlingoSdk' do
  project 'BoostlingoSdk.xcodeproj'
  pod 'BoostlingoSDK', '1.0.1'
end

